######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 11 19:54:58 2014
######################################################################
QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /usr/include/libfreenect/
LIBS += /usr/lib/libfreenect.dylib 

# Input
HEADERS += matrixwidget.h window.h
SOURCES += matrixwidget.cpp main.cpp window.cpp
