######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 11 19:54:58 2014
######################################################################
QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
INCLUDEPATH += /Users/dintskirveli/libfreenect/include
LIBS += /Users/dintskirveli/libfreenect/build/lib/libfreenect.dylib 

# Input
HEADERS += matrixwidget.h window.h
SOURCES += matrixwidget.cpp main.cpp window.cpp
